server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: ritsu
    password: "mSdo!F:!)U5-"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
  main:
    web-application-type: servlet
